version: "1.0"
info:
  model: int-scaffold
packages:
- name: SanthoshKProject
  gitServerName: SanthoshK
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
services:
- serviceName: project.santhoshk.integrations:t1
  packages:
  - name: SanthoshKProject
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.1131
